"""QUAD SDK Tools — SNPE/QAIRT tool reference, platform matrix, and CLI builders."""

from quad.sdk_tools.platform_matrix import (
    ToolPlatform,
    ToolCategory,
    ToolDescriptor,
    SDK_TOOLS,
    PLATFORM_NOTES,
    get_tools_for_platform,
    get_tools_by_category,
    is_tool_available,
)
from quad.sdk_tools.tool_specs import (
    # Enums
    InputEncoding,
    InputLayout,
    InputType,
    FloatBitwidth,
    QuantBitwidth,
    MaskedSoftmaxMode,
    ExportFormat,
    TargetBackend,
    PerfProfile,
    ProfilingLevelNet,
    CacheCompatibilityMode,
    GpuMode,
    PriorityHint,
    RuntimeOrder,
    QuantCalibration,
    QuantSchema,
    # Data classes
    ConverterInputSpec,
    # CLI Builders
    OnnxConverterArgs,
    QairtConverterArgs,
    QairtQuantizerArgs,
    SnpeNetRunArgs,
    DiagviewArgs,
    DlcInfoArgs,
    DlcDiffArgs,
    # Constants
    DIAGVIEW_TIMING_LAYERS,
    DIAGVIEW_NOTES,
)
from quad.sdk_tools.architecture_checker import (
    ARCH_CHECKER_NOTES,
    ArchCheckerArgs,
    ArchCheckerIssue,
    ArchCheckerReport,
    KNOWN_ISSUES,
    KNOWN_RULES,
    ModificationStatus,
    ModifyMode,
    TOOL_NAME as ARCH_CHECKER_TOOL_NAME,
    find_arch_checker,
    parse_arch_checker_csv,
    run_arch_checker,
)

from quad.sdk_tools.accuracy_debugger import (
    ACCURACY_DEBUGGER_NOTES,
    AccDebuggerArchitecture,
    AccDebuggerFramework,
    AccDebuggerMode,
    AccDebuggerRuntime,
    AccPrecision,
    CompareEncodingsArgs,
    E2EAccuracyDebuggerArgs,
    FrameworkRunnerArgs,
    InferenceEngineArgs,
    InferenceEngineStage,
    InputTensorSpec,
    QuantAlgorithm,
    QuantCheckerAlgorithmConfig,
    QuantCheckerConfig,
    TensorDataType,
    TensorInspectionArgs,
    TensorMappingConfig,
    VerificationArgs,
    VerifierConfig,
    VerifierSpec,
    VerifierType,
    get_framework_runner_output_dir,
    get_graph_struct_path,
    get_inference_engine_output_dir,
    get_tensor_mapping_path,
    get_verification_result_dir,
)

__all__ = [
    # Platform matrix
    "ToolPlatform",
    "ToolCategory",
    "ToolDescriptor",
    "SDK_TOOLS",
    "PLATFORM_NOTES",
    "get_tools_for_platform",
    "get_tools_by_category",
    "is_tool_available",
    # Enums (tool_specs)
    "InputEncoding",
    "InputLayout",
    "InputType",
    "FloatBitwidth",
    "QuantBitwidth",
    "MaskedSoftmaxMode",
    "ExportFormat",
    "TargetBackend",
    "PerfProfile",
    "ProfilingLevelNet",
    "CacheCompatibilityMode",
    "GpuMode",
    "PriorityHint",
    "RuntimeOrder",
    "QuantCalibration",
    "QuantSchema",
    # Data classes (tool_specs)
    "ConverterInputSpec",
    # CLI Builders (tool_specs)
    "OnnxConverterArgs",
    "QairtConverterArgs",
    "QairtQuantizerArgs",
    "SnpeNetRunArgs",
    "DiagviewArgs",
    "DlcInfoArgs",
    "DlcDiffArgs",
    # Constants (tool_specs)
    "DIAGVIEW_TIMING_LAYERS",
    "DIAGVIEW_NOTES",
    # Architecture Checker
    "ARCH_CHECKER_NOTES",
    "ARCH_CHECKER_TOOL_NAME",
    "ArchCheckerArgs",
    "ArchCheckerIssue",
    "ArchCheckerReport",
    "KNOWN_ISSUES",
    "KNOWN_RULES",
    "ModificationStatus",
    "ModifyMode",
    "find_arch_checker",
    "parse_arch_checker_csv",
    "run_arch_checker",
    # Accuracy Debugger
    "ACCURACY_DEBUGGER_NOTES",
    "AccDebuggerArchitecture",
    "AccDebuggerFramework",
    "AccDebuggerMode",
    "AccDebuggerRuntime",
    "AccPrecision",
    "CompareEncodingsArgs",
    "E2EAccuracyDebuggerArgs",
    "FrameworkRunnerArgs",
    "InferenceEngineArgs",
    "InferenceEngineStage",
    "InputTensorSpec",
    "QuantAlgorithm",
    "QuantCheckerAlgorithmConfig",
    "QuantCheckerConfig",
    "TensorDataType",
    "TensorInspectionArgs",
    "TensorMappingConfig",
    "VerificationArgs",
    "VerifierConfig",
    "VerifierSpec",
    "VerifierType",
    "get_framework_runner_output_dir",
    "get_graph_struct_path",
    "get_inference_engine_output_dir",
    "get_tensor_mapping_path",
    "get_verification_result_dir",
]
