"""HNRD (Hexagon NPU Runtime Driver) utilities for Windows.

HNRD is pre-installed on Windows Snapdragon X Series devices (packaged with BSP).
It allows applications to use platform-dependent HTP libraries installed on the
system instead of bundling them with the app.

Path Selection (automatic — no code changes needed):
  Traditional: app bundles SnpeHtpVXXStub.dll + SnpeHtpVXXSkel.so → uses bundled libs
  HNRD:        app does NOT bundle platform libs → falls back to HNRD system driver

  Key: "no difference in the build step between traditional and HNRD paths"
  Simply omit the platform-dependent DLLs from your deployment to use HNRD.

File mapping:
  Traditional               →  HNRD
  SnpeHtpPrepare.dll        →  QnnHtpPrepareDrv.dll
  SnpeHtpV73Stub.dll        →  QnnHtpV73StubDrv.dll
  SnpeHtpV73Skel.so         →  libQnnHtpV73SkelDrv.so
  (all in SDK)              →  HtpUsrDrv.dll  (pre-installed, in Driver Package)

Minimum SDK version: SNPE 2.22.2 (QNN 2.22.2)

HNRD log signature:
  [WARNING] QnnDsp <W> Traditional path not available. Switching to user driver path
  [WARNING] QnnDsp <W> HTP user driver is loaded. Switched to user driver path

Cache Compatibility:
  HNRD can be upgraded/downgraded independently of the app.
  A cache generated by one HNRD version may be sub-optimal or invalid on another.
  Snpe_SNPEBuilder_Build() / SNPEBuilder::build() auto-check compatibility.
  Use SetCacheCompatibilityMode to control sub-optimal cache behavior.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


# ══════════════════════════════════════════════════════════════════════════════
# HNRD Constants
# ══════════════════════════════════════════════════════════════════════════════

HNRD_MIN_SDK_VERSION = "2.22.2"

# Log messages indicating HNRD path is active
HNRD_LOG_TRADITIONAL_NOT_AVAILABLE = "Traditional path not available. Switching to user driver path"
HNRD_LOG_DRIVER_LOADED = "HTP user driver is loaded. Switched to user driver path"

# Platform-dependent files: present → traditional path; absent → HNRD path
TRADITIONAL_PATH_FILES = [
    "SnpeHtpPrepare.dll",
    "SnpeHtpV{XX}Stub.dll",   # XX = hexagon version (e.g. 73)
    "SnpeHtpV{XX}Skel.so",
]

# HNRD driver package files (pre-installed on device, NOT in SNPE SDK)
HNRD_DRIVER_FILES = [
    "HtpUsrDrv.dll",
    "QnnHtpPrepareDrv.dll",
    "QnnHtpV{XX}StubDrv.dll",
    "libQnnHtpV{XX}SkelDrv.so",
]

# Error codes for cache compatibility failures
SNPE_ERRORCODE_DLCACHING_SUBOPTIMAL_CACHE = "SNPE_ERRORCODE_DLCACHING_SUBOPTIMAL_CACHE"
SNPE_ERRORCODE_QNN_CONTEXT_ERROR_CREATE_FROM_BINARY = "SNPE_ERRORCODE_QNN_CONTEXT_ERROR_CREATE_FROM_BINARY"
SNPE_ERRORCODE_QNN_COMMON_ERROR_NOT_SUPPORTED = "SNPE_ERRORCODE_QNN_COMMON_ERROR_NOT_SUPPORTED"


# ══════════════════════════════════════════════════════════════════════════════
# Cache Compatibility Modes
# ══════════════════════════════════════════════════════════════════════════════

class CacheCompatibilityMode(str, Enum):
    """Controls how SNPE handles cache compatibility checks with HNRD.

    HNRD can be upgraded/downgraded independently of the app,
    so a previously saved cache may be sub-optimal or invalid.

    C API: Snpe_SNPEBuilder_SetCacheCompatibilityMode()
    C++  : snpeBuilder.setCacheCompatibilityMode()
    """
    STRICT = "SNPE_CACHE_COMPATIBILITY_STRICT"
    """Fail if cache is sub-optimal. Fail if cache is invalid.
    Use to detect when a cache needs regeneration."""

    PERMISSIVE = "SNPE_CACHE_COMPATIBILITY_PERMISSIVE"
    """Allow sub-optimal cache to load (use with caution).
    Use when you want to keep serving with old cache while regenerating."""

    ALWAYS_GENERATE_NEW_CACHE = "SNPE_CACHE_COMPATIBILITY_ALWAYS_GENERATE_NEW_CACHE"
    """Force regeneration of cache regardless of existing cache state.
    Use with SetInitCacheMode(true) to save the new cache."""

    @property
    def description(self) -> str:
        return {
            "SNPE_CACHE_COMPATIBILITY_STRICT": (
                "Fail on sub-optimal OR invalid cache. "
                "Check error code: SUBOPTIMAL → use PERMISSIVE; "
                "CREATE_FROM_BINARY/NOT_SUPPORTED → use ALWAYS_GENERATE_NEW_CACHE."
            ),
            "SNPE_CACHE_COMPATIBILITY_PERMISSIVE": (
                "Allow sub-optimal cache to load. "
                "Use while regenerating better cache in background thread."
            ),
            "SNPE_CACHE_COMPATIBILITY_ALWAYS_GENERATE_NEW_CACHE": (
                "Force cache regeneration. Combine with SetInitCacheMode(true) "
                "to save the new cache. Run in background thread for zero latency."
            ),
        }.get(self.value, "")


# ══════════════════════════════════════════════════════════════════════════════
# HNRD Path Detection
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class HNRDDeploymentConfig:
    """Deployment configuration for HNRD vs traditional path.

    Traditional path: bundle HTP platform libs with app.
    HNRD path: don't bundle — SNPE.dll falls back to system driver.

    There is NO difference in build steps. Path is selected at runtime
    based on whether the platform-dependent DLLs are present.
    """
    use_hnrd: bool = False
    hexagon_version: str = "v73"

    @property
    def files_to_bundle(self) -> list[str]:
        """List of DLL/SO files to include in app deployment.

        Traditional path: include all platform-dependent files.
        HNRD path: only bundle SNPE.dll (platform-agnostic).
        """
        ver = self.hexagon_version.lstrip("v")
        if self.use_hnrd:
            # HNRD: only SNPE.dll needed; driver handles platform libs
            return ["SNPE.dll"]
        else:
            # Traditional: bundle all platform-dependent libs
            return [
                "SNPE.dll",
                "SnpeHtpPrepare.dll",
                f"SnpeHtpV{ver}Stub.dll",
                f"SnpeHtpV{ver}Skel.so",
            ]

    @property
    def path_name(self) -> str:
        return "HNRD (system driver)" if self.use_hnrd else "Traditional (bundled)"


def is_hnrd_log(log_line: str) -> bool:
    """Check if a log line indicates HNRD path is active."""
    return (
        HNRD_LOG_TRADITIONAL_NOT_AVAILABLE in log_line
        or HNRD_LOG_DRIVER_LOADED in log_line
    )


def get_cache_error_type(error_code: str) -> str:
    """Classify a cache error as 'suboptimal', 'invalid', or 'other'."""
    if error_code == SNPE_ERRORCODE_DLCACHING_SUBOPTIMAL_CACHE:
        return "suboptimal"
    if error_code in (
        SNPE_ERRORCODE_QNN_CONTEXT_ERROR_CREATE_FROM_BINARY,
        SNPE_ERRORCODE_QNN_COMMON_ERROR_NOT_SUPPORTED,
    ):
        return "invalid"
    return "other"


def get_cache_recovery_strategy(error_code: str) -> dict:
    """Return the recommended cache recovery strategy for an error code.

    Based on the HNRD cache management example from the docs.
    """
    error_type = get_cache_error_type(error_code)
    if error_type == "suboptimal":
        return {
            "immediate_action": CacheCompatibilityMode.PERMISSIVE,
            "background_action": CacheCompatibilityMode.ALWAYS_GENERATE_NEW_CACHE,
            "enable_init_cache": True,
            "description": (
                "Sub-optimal cache: continue with current cache, "
                "regenerate better cache in background thread."
            ),
        }
    if error_type == "invalid":
        return {
            "immediate_action": CacheCompatibilityMode.ALWAYS_GENERATE_NEW_CACHE,
            "background_action": None,
            "enable_init_cache": True,
            "description": (
                "Invalid cache: force regeneration now. "
                "If regeneration fails, HNRD is too old — prompt user to upgrade."
            ),
        }
    return {
        "immediate_action": None,
        "background_action": None,
        "enable_init_cache": False,
        "description": "Unknown error — check Snpe_ErrorCode_getLastErrorCode()",
    }
